image: ruby:2.5.0

cache:
  paths:
    - vendor/bundle
    - node_modules

services:
  - postgres:10.4

variables:
  BUNDLE_PATH: vendor/bundle
  DISABLE_SPRING: 1

before_script:
  # Install node and some other deps
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt-get update -yq
  - apt-get install -y apt-transport-https build-essential cmake nodejs unzip

  # Install yarn
  - wget -q -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
  - apt-get update -yq
  - apt-get install -y yarn

  # Project setup
  - bundle check || bundle install --jobs $(nproc)
  - yarn install

  - cp config/database.yml.ci config/database.yml
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:schema:load RAILS_ENV=test

stages:
  - test
  - lint
  - deploy

Tests:
  stage: test
  script:
    - bundle exec rspec

Pronto:
  before_script:
    - gem install pronto-rubocop
  stage: lint
  allow_failure: true
  except:
    - master
  script:
    - bundle exec pronto run -f gitlab -c origin/master

variables:
  APP_NAME: staging-dyno

deploy_staging:
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 'backpacking.fr' >> ~/.ssh/known_hosts
  stage: deploy
  only:
    - master
  environment:
    name: staging
    url: https://dev.backpacking.fr
  script:
    - git push dokku@backpacking.fr:staging-dyno master
