Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'db/**/*.rb'
    - 'bin/**/*'

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
